language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
matrix:
  allow_failures:
    - node_js: "9"
  include:
    - node_js: "8"
      env: TEST_GRAPHICSMAGICK=TRUE
    - node_js: "8"
      env: TEST_IMAGEMAGICK=TRUE
    - node_js: "8"
      env: TEST_IMAGEMAGICK=IMPLICIT
    - node_js: "8"
      env: TEST_IMAGEMAGICK=IMPLICIT_WITH_SET

before_install:
  # Upgrade `npm` to avoid semver issues
  - npm install npm@1.x.x -g

install:
  # Run our install script
  - test/install.sh

  # Output the im/gm version
  - if test -n "$TEST_IMAGEMAGICK"; then convert -version; else gm -version; fi

  # Install dependencies
  - npm install

script:
  - npm test

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
