language: node_js
node_js:
  # - "0.11"
  - "0.10"
#   - "0.8"
# matrix:
#   allow_failures:
#     - node_js: "0.11"
env:
  # TODO: Verify that the `||` logic in preinstall will work in Windows
  - TEST_IMAGEMAGICK=TRUE

install:
  # Install imagemagick
  - sudo apt-get install imagemagick -y

  # Install dependencies
  - npm install

script:
  - npm test

notifications:
  email: false
