language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"

install:
  # Install graphicsmagick
  - sudo apt-get install graphicsmagick -y

  # Output phantomjs version
  - gm version

  # Install dependencies
  - npm install

notifications:
  email: false
