language: node_js
node_js:
  # - "0.11"
  - "0.10"
#   - "0.8"
# matrix:
#   allow_failures:
#     - node_js: "0.11"
env:
  # TODO: Verify that the `||` logic in preinstall will work in Windows
  - TEST_GRAPHICSMAGICK=TRUE
  - TEST_IMAGEMAGICK=TRUE

install:
  # Run our install script
  - test/install.sh

  # Output the im/gm version
  - if which convert 2> /dev/null; then convert -version; else gm -version; fi

  # Install dependencies
  - npm install

script:
  - npm test

notifications:
  email: false
